apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.image.configMap }}-deployer"
  labels:
    type: topmall-api
data:
  args.conf: |
    # Apply this config
    -Dserver.port=${randomServerPort.value[1200,2000]}
    -Ddubbo.service.version=1.1.0
    -Ddubbo.consumer.version=1.1.0
    -Ddubbo.protocol.port=-1
    -Ddubbo.protocol.dubbo.port=-1
    -Djava.security.egd=file:/dev/./urandom
    -Dspring.profiles.active=default,{{ .Values.env }}
    -Ddubbo.shutdown.hook=true
    -DlogFilePath=../logs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.image.configMap }}-web"
  labels:
    type: topmall-web
data:
  args.conf: |
    # Apply this config
    -Dserver.port=8080
    -Ddubbo.service.version=1.1.0
    -Ddubbo.consumer.version=1.1.0
    -Ddubbo.protocol.port=20880
    -Ddubbo.protocol.dubbo.port=20880
    -Djava.security.egd=file:/dev/./urandom
    -Dspring.profiles.active=default,{{ .Values.env }}
    -Ddubbo.shutdown.hook=true
    -DlogFilePath=../logs